# Generated by Django 4.0.2 on 2022-02-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_user_alter_profile_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
