# Generated by Django 4.0.2 on 2022-02-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discounts',
        ),
    ]
